- name: add section in config file
  lineinfile:
    path: /etc/gitea/config.ini
    regexp: '^\[({{ section.key }}|{{ section.key|upper }})\]'
    line: '[{{ section.key }}]'
    create: yes
  notify: restart gitea
  when: section.key != 'default'

- name: add option in config file
  lineinfile:
    path: /etc/gitea/config.ini
    regexp: '^{{ item.key|upper }}\s+='
    line: '{{ item.key|upper }} = {{ item.value }}'
    insertafter: '[{{ section.key }}]'
  with_dict: '{{ section.value }}'
  notify: restart gitea
  when: section.key != 'default'

- name: add option in config file
  lineinfile:
    path: /etc/gitea/config.ini
    regexp: '^{{ item.key|upper }}\s+='
    line: '{{ item.key|upper }} = {{ item.value }}'
    insertbefore: BOF
    create: yes
  with_dict: '{{ section.value }}'
  notify: restart gitea
  when: section.key == 'default'
